# Generated by Django 5.1 on 2024-10-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_visitor_gender_alter_visitor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='discription',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
