# Generated by Django 5.1 on 2024-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_visitor_discription_alter_visitor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('check-in', 'check-in'), ('check-out', 'check-out')], default='check-in', max_length=20),
        ),
    ]
