# Generated by Django 5.1 on 2024-10-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_visitor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='ctime',
            field=models.TimeField(default='--'),
        ),
    ]
