# Generated by Django 5.1 on 2024-10-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_visitor_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ctime',
            field=models.TimeField(auto_now=True),
        ),
    ]
