# Generated by Django 5.1 on 2024-10-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_visitor_ctime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='ctime',
        ),
    ]
