# Generated by Django 5.1.2 on 2024-10-26 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_visitor_ctime_visitor_status'),
        ('app1', '0011_visitor_ctime'),
    ]

    operations = [
    ]
