# Generated by Django 5.1.1 on 2024-10-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_visitor_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ctime',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
