# Generated by Django 5.1.2 on 2024-10-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_visitor_ctime'),
        ('app1', '0012_merge_20241026_1202'),
    ]

    operations = [
    ]
