# Generated by Django 5.1 on 2024-10-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_visitor_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='discription',
            field=models.TextField(),
        ),
    ]
