# Generated by Django 5.1.2 on 2024-11-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_visitor_discription'),
        ('app1', '0013_merge_20241028_1104'),
    ]

    operations = [
    ]
