# Generated by Django 5.1.2 on 2024-11-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_merge_20241102_1223'),
        ('app1', '0014_merge_20241104_1157'),
    ]

    operations = [
    ]
