# Generated by Django 5.1 on 2024-11-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_merge_20241104_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='discription',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
