# Generated by Django 5.1 on 2024-11-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_visitor_discription'),
        ('app1', '0017_sub_name'),
    ]

    operations = [
    ]
